name: SubeteLobby
main: uk.co.hubza.subetelobby.subetelobby
version: 1.0

commands:
   test:
      description: This is a demo command.
      usage: /<command> [player]
      permission: SubeteLobby.test
      permission-message: You don't have <permission>

permissions:
    SubeteLobby.test:
        description: super secret test plugin
        default: op